### ISSUE TITLE
One to one gesture support as in elementary os and gnome's latest gesture implementation? 

### ISSUE THREAD

**Issue by DuttaAB-dev** [pop-os/touchegg#1]

**Comment by Nequo** [comment]
Hi, is there any plans for implementing this at all? Thanks!

**Comment by andirsun** [comment]
Hi!, you can install the x11 gesture extention https://extensions.gnome.org/extension/4033/x11-gestures/ (1:1 gestures on pop os)
and touche on flathub to modify the gestures if you want https://flathub.org/apps/details/com.github.joseexposito.touche

**Comment by 13r0ck** [comment]
This has been fixed for a while, just forgot to close. Thanks!
